In [1]:
import pandas as pd

In [2]:
pd.__version__

u'0.23.4'

In [3]:
fp = '/Volumes/WDC_internal/Users/bell/ecoraid/2018/Moorings/18mtp1a/rawconverted/sbe26/18mtp1a_narr_apress.orig.tid'

In [4]:
rawdata = pd.read_csv(fp,delimiter='\s+', skiprows=1,names=['date','time','psia','degC'])

In [8]:
rawdata = rawdata.set_index(pd.DatetimeIndex(rawdata['date']+' '+rawdata['time']))
rawdata.drop(['date','time'],1,inplace=True)

In [9]:
rawdata.index=rawdata.index.round('15min',inplace=True)

In [11]:
rawdata['date_time'] = rawdata.index

In [12]:
rawdata

                        psia    degC           date_time
2018-05-04 18:15:00  -0.1783  10.157 2018-05-04 18:15:00
2018-05-04 18:30:00  -0.1665  10.315 2018-05-04 18:30:00
2018-05-04 18:45:00  -0.1380  11.618 2018-05-04 18:45:00
2018-05-04 19:00:00  -0.1622  10.207 2018-05-04 19:00:00
2018-05-04 19:15:00  -0.1815   5.946 2018-05-04 19:15:00
2018-05-04 19:30:00  -0.2066   3.785 2018-05-04 19:30:00
2018-05-04 19:45:00  -0.2133   2.248 2018-05-04 19:45:00
2018-05-04 20:00:00  -0.2074   1.417 2018-05-04 20:00:00
2018-05-04 20:15:00  -0.1981   1.144 2018-05-04 20:15:00
2018-05-04 20:30:00  -0.1947   0.876 2018-05-04 20:30:00
2018-05-04 20:45:00  -0.1913   0.824 2018-05-04 20:45:00
2018-05-04 21:00:00  -0.1862   1.000 2018-05-04 21:00:00
2018-05-04 21:15:00  -0.1753   1.677 2018-05-04 21:15:00
2018-05-04 21:30:00  -0.1726   1.840 2018-05-04 21:30:00
2018-05-04 21:45:00  -0.1658   2.835 2018-05-04 21:45:00
2018-05-04 22:00:00  -0.1606   2.996 2018-05-04 22:00:00
2018-05-04 22:15:00  -0.1614   2.848 2018-05-04 22:15:00
2018-05-04 22:30:00  -0.1621   2.525 2018-05-04 22:30:00
2018-05-04 22:45:00  -0.1645   2.319 2018-05-04 22:45:00
2018-05-04 23:00:00  -0.1643   2.267 2018-05-04 23:00:00
2018-05-04 23:15:00  -0.1625   2.248 2018-05-04 23:15:00
2018-05-04 23:30:00  -0.1607   2.338 2018-05-04 23:30:00
2018-05-04 23:45:00  -0.1573   2.357 2018-05-04 23:45:00
2018-05-05 00:00:00  -0.1521   2.616 2018-05-05 00:00:00
2018-05-05 00:15:00  -0.1564   2.803 2018-05-05 00:15:00
2018-05-05 00:30:00  -0.1583   3.041 2018-05-05 00:30:00
2018-05-05 00:45:00  -0.1585   3.144 2018-05-05 00:45:00
2018-05-05 01:00:00  -0.1613   3.535 2018-05-05 01:00:00
2018-05-05 01:15:00  -0.1640   3.523 2018-05-05 01:15:00
2018-05-05 01:30:00  -0.1652   3.952 2018-05-05 01:30:00
...                      ...     ...                 ...
2018-10-10 16:45:00  92.8829   3.952 2018-10-10 16:45:00
2018-10-10 17:00:00  92.8862   3.952 2018-10-10 17:00:00
2018-10-10 17:15:00  92.8862   3.952 2018-10-10 17:15:00
2018-10-10 17:30:00  92.8854   3.952 2018-10-10 17:30:00
2018-10-10 17:45:00  92.8694   3.958 2018-10-10 17:45:00
2018-10-10 18:00:00  92.8518   3.952 2018-10-10 18:00:00
2018-10-10 18:15:00  92.8376   3.952 2018-10-10 18:15:00
2018-10-10 18:30:00  92.8166   3.952 2018-10-10 18:30:00
2018-10-10 18:45:00  92.7981   3.952 2018-10-10 18:45:00
2018-10-10 19:00:00  92.7645   3.952 2018-10-10 19:00:00
2018-10-10 19:15:00  92.7293   3.946 2018-10-10 19:15:00
2018-10-10 19:30:00  92.6991   3.946 2018-10-10 19:30:00
2018-10-10 19:45:00  92.6731   3.939 2018-10-10 19:45:00
2018-10-10 20:00:00  92.6345   3.933 2018-10-10 20:00:00
2018-10-10 20:15:00  92.5933   3.933 2018-10-10 20:15:00
2018-10-10 20:30:00  92.5447   3.926 2018-10-10 20:30:00
2018-10-10 20:45:00  92.5010   3.920 2018-10-10 20:45:00
2018-10-10 21:00:00  92.4473   3.920 2018-10-10 21:00:00
2018-10-10 21:15:00  92.4020   3.920 2018-10-10 21:15:00
2018-10-10 21:30:00  92.3525   3.913 2018-10-10 21:30:00
2018-10-10 21:45:00  92.3072   3.913 2018-10-10 21:45:00
2018-10-10 22:00:00  92.2686   3.913 2018-10-10 22:00:00
2018-10-10 22:15:00  92.2392   3.913 2018-10-10 22:15:00
2018-10-10 22:30:00  45.4970   8.578 2018-10-10 22:30:00
2018-10-10 22:45:00  -0.2986   9.689 2018-10-10 22:45:00
2018-10-10 23:00:00  -0.2633   9.955 2018-10-10 23:00:00
2018-10-10 23:15:00  -0.2717  10.365 2018-10-10 23:15:00
2018-10-10 23:30:00  -0.2809  10.751 2018-10-10 23:30:00
2018-10-10 23:45:00  -0.2809  11.364 2018-10-10 23:45:00
2018-10-11 00:00:00  -0.2818  13.586 2018-10-11 00:00:00

[15288 rows x 3 columns]